version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: grocery_app
      MYSQL_USER: sourabh
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3307"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
